theme_version: 1.0.2

# Site settings
title:              Valenzia Lafratta
logo:               # Logo image URL
description:        Illustratrice e docente
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://valenzialafratta.github.io/'
#twitter:            https://twitter.com/aspirethemes
#facebook:           https://www.facebook.com/aspirethemes
instagram:          https://www.instagram.com/valenzia_l

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
